language: ruby
cache: bundler
rvm:
  - 2.2
  - ruby-head
  - 2.0
  - 2.1
  - rbx-2
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create db:migrate db:test:prepare
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
notifications:
  email:
    - tj+scube_server@a13.fr
